# window
remember_window_size                no
initial_window_width                72c
initial_window_height               18c
linux_display_server                x11

# background
background_image                    ~/.config/fastfetch/assets/kitty_wallpaper.png
background_image_layout             scaled
background_tint                     0.6

# tab_bar
# tab_bar_edge                        bottom    
# tab_bar_style                       powerline
# tab_bar_align                       left
# tab_bar_min_tabs                    1
# tab_powerline_style                 slanted

# cursor
cursor_trail                        100
cursor_trail_decay                  0.1 0.2
cursor_trail_start_threshold        1
