
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "kitty"
local fileManager = "dolphin"
local menu = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("waybar & hyprpaper")
  hl.exec_cmd("hyprpolkitagent")
  hl.exec_cmd("wl-paste --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
        force_split    = 2,    -- new window always opens on the right/bottom, current one shifts left/top
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper   = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo     = false, -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering  = true,  -- Disable the random "RIP hyprlang" style splash text
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "pt",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
------------------------------------------------------------------------
-- Floating quadrant terminal helpers
--
-- Shared grid: usable area (monitor minus reserved space, e.g. waybar)
-- split with symmetric outer/inner gaps so the four quadrant windows
-- line up whether you open one or all four.
------------------------------------------------------------------------
local quadGapOut = 16
local quadGapIn  = 10
local quadClass  = "kitty-quad" -- SUPER + SHIFT + Q: one quadrant, follows the cursor

-- Usable-area grid for a monitor, plus which half/quadrant a cursor pos falls in
local function usableGrid(mon, pos)
    local r = mon.reserved or { top = 0, bottom = 0, left = 0, right = 0 }
    local ux, uy = mon.x + r.left, mon.y + r.top
    local uw = mon.width  / mon.scale - r.left - r.right
    local uh = mon.height / mon.scale - r.top  - r.bottom

    local qw = (uw - 2 * quadGapOut - quadGapIn) / 2
    local qh = (uh - 2 * quadGapOut - quadGapIn) / 2
    local xL, xR = ux + quadGapOut, ux + quadGapOut + qw + quadGapIn
    local yT, yB = uy + quadGapOut, uy + quadGapOut + qh + quadGapIn

    local isLeft, isTop = true, true
    if pos then
        isLeft = (pos.x - ux) < uw / 2
        isTop  = (pos.y - uy) < uh / 2
    end

    return {
        ux = ux, uy = uy, uw = uw, uh = uh,
        qw = qw, qh = qh, xL = xL, xR = xR, yT = yT, yB = yB,
        isLeft = isLeft, isTop = isTop,
    }
end

-- The four top-level quadrant boxes for a monitor's usable-area grid
local function quadrantSlots(g)
    return {
        TL = { x = g.xL, y = g.yT, w = g.qw, h = g.qh },
        TR = { x = g.xR, y = g.yT, w = g.qw, h = g.qh },
        BL = { x = g.xL, y = g.yB, w = g.qw, h = g.qh },
        BR = { x = g.xR, y = g.yB, w = g.qw, h = g.qh },
    }
end

local function spawnInBox(cmd, class, box)
    hl.exec_cmd(cmd .. " --class " .. class, {
        float = true,
        move  = string.format("%d %d", math.floor(box.x), math.floor(box.y)),
        size  = string.format("%d %d", math.floor(box.w), math.floor(box.h)),
    })
end

-- resize first: Hyprland grows/shrinks floating windows from their
-- center, so moving afterwards is what actually lands them in place
local function placeActiveWindow(box)
    hl.dispatch(hl.dsp.window.resize({ x = math.floor(box.w), y = math.floor(box.h), relative = false }))
    hl.dispatch(hl.dsp.window.move({ x = math.floor(box.x), y = math.floor(box.y) }))
end

------------------------------------------------------------------------
-- SUPER + Q: open a terminal filling the quadrant under the cursor.
-- If the cursor is already over a SUPER + Q terminal (e.g. pressed again
-- without moving the mouse), that terminal's space is split in half
-- instead — the existing terminal keeps one half, the new one takes the
-- other. This recurses: pressing it again in the same spot splits again.
------------------------------------------------------------------------
local function boxesOverlap(a, b)
    return a.x < b.x + b.w and a.x + a.w > b.x and a.y < b.y + b.h and a.y + a.h > b.y
end

-- Any SUPER + Q terminal that overlaps the target quadrant already claims
-- it — pick the one closest to the cursor (handles the quadrant already
-- being split into halves, and small cursor drift landing in the gap
-- between them). Must be on the same workspace: floating windows keep
-- the same pixel coordinates across workspaces, so without this a
-- terminal left behind on another workspace would look like it's here.
local function findSplitTarget(pos, monId, wsId, quadrantBox)
    local best, bestDist
    for _, w in ipairs(hl.get_windows({ class = quadClass, floating = true })) do
        if w.monitor and w.monitor.id == monId and w.workspace and w.workspace.id == wsId then
            local wb = { x = w.at.x, y = w.at.y, w = w.size.x, h = w.size.y }
            if boxesOverlap(wb, quadrantBox) then
                local cx, cy = wb.x + wb.w / 2, wb.y + wb.h / 2
                local dist = (pos.x - cx) ^ 2 + (pos.y - cy) ^ 2
                if not best or dist < bestDist then
                    best, bestDist = w, dist
                end
            end
        end
    end
    return best
end

-- Targets a specific (possibly unfocused) window: dispatchers only ever
-- act on the focused window, so focus it first.
local function placeWindow(win, box)
    hl.dispatch(hl.dsp.focus({ window = win }))
    placeActiveWindow(box)
end

local function openQuadrantTerm()
    local pos = hl.get_cursor_pos()
    local mon = hl.get_monitor_at_cursor()
    if not pos or not mon or not mon.active_workspace then
        hl.exec_cmd(terminal)
        return
    end

    local g = usableGrid(mon, pos)
    local quadrantBox = {
        x = g.isLeft and g.xL or g.xR,
        y = g.isTop  and g.yT or g.yB,
        w = g.qw, h = g.qh,
    }

    local existing = findSplitTarget(pos, mon.id, mon.active_workspace.id, quadrantBox)
    if existing then
        local bx, by, bw, bh = existing.at.x, existing.at.y, existing.size.x, existing.size.y
        local box1, box2
        if bw >= bh then
            local halfw = (bw - quadGapIn) / 2
            box1 = { x = bx, y = by, w = halfw, h = bh }
            box2 = { x = bx + halfw + quadGapIn, y = by, w = halfw, h = bh }
        else
            local halfh = (bh - quadGapIn) / 2
            box1 = { x = bx, y = by, w = bw, h = halfh }
            box2 = { x = bx, y = by + halfh + quadGapIn, w = bw, h = halfh }
        end

        placeWindow(existing, box1)
        spawnInBox(terminal, quadClass, box2)
        return
    end

    spawnInBox(terminal, quadClass, quadrantBox)
end

hl.bind(mainMod .. " + Q", openQuadrantTerm)

------------------------------------------------------------------------
-- SUPER + SHIFT + Q: default Arch/Hyprland behavior, unchanged (tiled terminal)
------------------------------------------------------------------------
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd(terminal))

------------------------------------------------------------------------
-- SUPER + SPACE: if exactly one of the 4 quadrants (SUPER + Q terminals)
-- is empty, expand the focused quadrant terminal into it, provided the
-- empty quadrant shares an edge with it (same row or column). Pressing
-- SUPER + SPACE again on that now-expanded terminal shrinks it back to
-- its original quadrant.
------------------------------------------------------------------------
local function boxesMatch(a, b, tol)
    tol = tol or 20
    return math.abs(a.x - b.x) <= tol and math.abs(a.y - b.y) <= tol
       and math.abs(a.w - b.w) <= tol and math.abs(a.h - b.h) <= tol
end

local expandedFrom = {} -- window address -> { home = quadrant box, expanded = filled box }

local function fillEmptyQuadrant()
    local win = hl.get_active_window()
    if not win or win.class ~= quadClass or not win.monitor or not win.workspace then return end

    local winBox = { x = win.at.x, y = win.at.y, w = win.size.x, h = win.size.y }

    -- Already expanded from a previous SUPER + SPACE: shrink back home
    local prev = expandedFrom[win.address]
    if prev and boxesMatch(winBox, prev.expanded) then
        placeActiveWindow(prev.home)
        expandedFrom[win.address] = nil
        return
    end

    local g = usableGrid(win.monitor)
    local slots = quadrantSlots(g)

    local activeKey
    for key, box in pairs(slots) do
        if boxesMatch(box, winBox) then activeKey = key end
    end
    if not activeKey then return end

    -- A quadrant counts as occupied if ANY terminal overlaps it, not just
    -- one that exactly fills it — otherwise a quadrant split into halves
    -- (SUPER + Q pressed twice in the same spot) looks empty here.
    local occupied = { TL = false, TR = false, BL = false, BR = false }
    occupied[activeKey] = true
    for _, w in ipairs(hl.get_windows({ class = quadClass, floating = true })) do
        if w.address ~= win.address and w.monitor and w.monitor.id == win.monitor.id
           and w.workspace and w.workspace.id == win.workspace.id then
            local box = { x = w.at.x, y = w.at.y, w = w.size.x, h = w.size.y }
            for key, slot in pairs(slots) do
                if boxesOverlap(slot, box) then occupied[key] = true end
            end
        end
    end

    local emptyKey, emptyCount = nil, 0
    for key, filled in pairs(occupied) do
        if not filled then emptyKey = key; emptyCount = emptyCount + 1 end
    end
    if emptyCount ~= 1 then return end -- only handle the "exactly one gap" case

    local sameRow = (activeKey == "TL" and emptyKey == "TR") or (activeKey == "TR" and emptyKey == "TL")
                 or (activeKey == "BL" and emptyKey == "BR") or (activeKey == "BR" and emptyKey == "BL")
    local sameCol = (activeKey == "TL" and emptyKey == "BL") or (activeKey == "BL" and emptyKey == "TL")
                 or (activeKey == "TR" and emptyKey == "BR") or (activeKey == "BR" and emptyKey == "TR")

    local box
    if sameRow then
        box = { x = g.xL, y = slots[activeKey].y, w = g.uw - 2 * quadGapOut, h = g.qh }
    elseif sameCol then
        box = { x = slots[activeKey].x, y = g.yT, w = g.qw, h = g.uh - 2 * quadGapOut }
    else
        return -- diagonal gap: no single rectangle covers it cleanly
    end

    expandedFrom[win.address] = { home = slots[activeKey], expanded = box }
    placeActiveWindow(box)
end

hl.bind(mainMod .. " + SPACE", fillEmptyQuadrant)

------------------------------------------------------------------------
-- SUPER + ALT + SHIFT + arrow: explicitly expand the focused quadrant
-- terminal towards a specific neighbor (up/down = same column, left/right
-- = same row), instead of SUPER + SPACE's "only if exactly one quadrant
-- is empty" auto-detect. Only works if the target quadrant is empty.
-- SUPER + SPACE still shrinks the result back to its original quadrant.
------------------------------------------------------------------------
local expandNeighbor = {
    up    = { TL = false, TR = false, BL = "TL", BR = "TR" },
    down  = { TL = "BL",  TR = "BR",  BL = false, BR = false },
    left  = { TL = false, TR = "TL",  BL = false, BR = "BL" },
    right = { TL = "TR",  TR = false, BL = "BR",  BR = false },
}

local function expandTowards(direction)
    local win = hl.get_active_window()
    if not win or win.class ~= quadClass or not win.monitor or not win.workspace then return end

    local g = usableGrid(win.monitor)
    local slots = quadrantSlots(g)
    local winBox = { x = win.at.x, y = win.at.y, w = win.size.x, h = win.size.y }

    local activeKey
    for key, box in pairs(slots) do
        if boxesMatch(box, winBox) then activeKey = key end
    end
    if not activeKey then return end

    local targetKey = expandNeighbor[direction][activeKey]
    if not targetKey then return end -- already at that edge

    for _, w in ipairs(hl.get_windows({ class = quadClass, floating = true })) do
        if w.address ~= win.address and w.monitor and w.monitor.id == win.monitor.id
           and w.workspace and w.workspace.id == win.workspace.id then
            local box = { x = w.at.x, y = w.at.y, w = w.size.x, h = w.size.y }
            if boxesOverlap(slots[targetKey], box) then return end -- target occupied
        end
    end

    local box
    if direction == "left" or direction == "right" then
        box = { x = g.xL, y = slots[activeKey].y, w = g.uw - 2 * quadGapOut, h = g.qh }
    else
        box = { x = slots[activeKey].x, y = g.yT, w = g.qw, h = g.uh - 2 * quadGapOut }
    end

    expandedFrom[win.address] = { home = slots[activeKey], expanded = box }
    placeActiveWindow(box)
end

hl.bind(mainMod .. " + ALT + SHIFT + up",    function() expandTowards("up") end)
hl.bind(mainMod .. " + ALT + SHIFT + down",  function() expandTowards("down") end)
hl.bind(mainMod .. " + ALT + SHIFT + left",  function() expandTowards("left") end)
hl.bind(mainMod .. " + ALT + SHIFT + right", function() expandTowards("right") end)

-- vim-style aliases (H/J/K/L): same rollover issue as SUPER + SHIFT + right
hl.bind(mainMod .. " + ALT + SHIFT + K", function() expandTowards("up") end)
hl.bind(mainMod .. " + ALT + SHIFT + J", function() expandTowards("down") end)
hl.bind(mainMod .. " + ALT + SHIFT + H", function() expandTowards("left") end)
hl.bind(mainMod .. " + ALT + SHIFT + L", function() expandTowards("right") end)

local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

-- Screenshots: PRINT = full (active monitor), SHIFT + PRINT = area select.
-- Saved to ~/media/screenshots, copied to clipboard, notified via dunst.
hl.bind("Print",          hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/screenshot.sh full"), { locked = true })
hl.bind("SHIFT + Print",  hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/screenshot.sh area"),  { locked = true })

hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Move/swap the active window with its neighbor in a direction.
-- For a floating window, "swap with the neighbor" doesn't make sense
-- (there's no tiling neighbor), and the direction dispatcher ends up
-- dragging it on top of the nearest window instead — so floating
-- windows get nudged by a fixed pixel step instead.
local function moveOrNudge(direction, dx, dy)
    return function()
        local win = hl.get_active_window()
        if win and win.floating then
            hl.dispatch(hl.dsp.window.move({ x = math.floor(win.at.x + dx), y = math.floor(win.at.y + dy) }))
        else
            hl.dispatch(hl.dsp.window.move({ direction = direction }))
        end
    end
end

local nudgeStep = 40
hl.bind(mainMod .. " + SHIFT + left",  moveOrNudge("l", -nudgeStep, 0))
hl.bind(mainMod .. " + SHIFT + right", moveOrNudge("r", nudgeStep, 0))
hl.bind(mainMod .. " + SHIFT + up",    moveOrNudge("u", 0, -nudgeStep))
hl.bind(mainMod .. " + SHIFT + down",  moveOrNudge("d", 0, nudgeStep))

-- vim-style aliases (H/J/K/L): SUPER + SHIFT + right seems to get lost on
-- this keyboard (likely rollover/ghosting on that specific key combo), so
-- these give a working fallback for all four directions.
hl.bind(mainMod .. " + SHIFT + H", moveOrNudge("l", -nudgeStep, 0))
hl.bind(mainMod .. " + SHIFT + L", moveOrNudge("r", nudgeStep, 0))
hl.bind(mainMod .. " + SHIFT + K", moveOrNudge("u", 0, -nudgeStep))
hl.bind(mainMod .. " + SHIFT + J", moveOrNudge("d", 0, nudgeStep))

-- Fullscreen (real) and maximize (keeps other windows behind)
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized" }))

-- Cycle focus to the next window / swap active window with the next one
hl.bind(mainMod .. " + Tab",   hl.dsp.window.cycle_next({ next = true }))
hl.bind(mainMod .. " + grave", hl.dsp.window.swap({ next = true }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Move active window to the next/previous workspace and follow it there
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ workspace = "+1", follow = true }))
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.move({ workspace = "-1", follow = true }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize the active window with the keyboard (works floating or tiled)
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.resize({ x = 30,  y = 0,   relative = true }), { repeating = true })
hl.bind(mainMod .. " + ALT + left",  hl.dsp.window.resize({ x = -30, y = 0,   relative = true }), { repeating = true })
hl.bind(mainMod .. " + ALT + up",    hl.dsp.window.resize({ x = 0,   y = -30, relative = true }), { repeating = true })
hl.bind(mainMod .. " + ALT + down",  hl.dsp.window.resize({ x = 0,   y = 30,  relative = true }), { repeating = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Firefox, VSCode, the file manager and zathura always open on the next
-- empty workspace, switching the view there, regardless of how they were launched.
hl.window_rule({
    name  = "firefox-workspace",
    match = { class = "^firefox$" },

    workspace = "empty",
})

hl.window_rule({
    name  = "vscode-workspace",
    match = { class = "^code$" },

    workspace = "empty",
})

hl.window_rule({
    name  = "filemanager-workspace",
    -- float = false excludes Dolphin's own dialogs/popups (Open With, properties,
    -- copy progress, etc.) which share the same class but open floating — they
    -- should stay on the current workspace instead of jumping to a new empty one.
    match = { class = "^org.kde.dolphin$", float = false },

    workspace = "empty",
})

hl.window_rule({
    name  = "zathura-workspace",
    match = { class = "^org.pwmt.zathura$" },

    workspace = "empty",
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
